Netgifx/src/br/com/fiap/netgifx/models/Gif.java
package br.com.fiap.netgifx.models;

public class Gif {

	private Long id;
	private String name;
	private String filename;
	private byte[] image;
	private Genre genre;
	private Language language;
	private Rating rating;
	private byte[] imageSnapshot;
	private Category category;
	
	public Gif() {
		super();
	}

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getFilename() {
		return filename;
	}
	public void setFilename(String filename) {
		this.filename = filename;
	}
	public byte[] getImage() {
		return image;
	}
	public void setImage(byte[] image) {
		this.image = image;
	}
	public Genre getGenre() {
		return genre;
	}
	public void setGenre(Genre genre) {
		this.genre = genre;
	}
	public Language getLanguage() {
		return language;
	}
	public void setLanguage(Language language) {
		this.language = language;
	}
	public Rating getRating() {
		return rating;
	}
	public void setRating(Rating rating) {
		this.rating = rating;
	}
	public byte[] getImageSnapshot() {
		return imageSnapshot;
	}
	public void setImageSnapshot(byte[] imageSnapshot) {
		this.imageSnapshot = imageSnapshot;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}
	
}

Netgifx/src/br/com/fiap/netgifx/managedbeans/GifController.java
package br.com.fiap.netgifx.managedbeans;

import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import org.primefaces.model.UploadedFile;

import br.com.fiap.netgifx.entities.CategoryEntity;
import br.com.fiap.netgifx.models.Genre;
import br.com.fiap.netgifx.models.Gif;
import br.com.fiap.netgifx.models.Language;
import br.com.fiap.netgifx.models.Rating;
import br.com.fiap.netgifx.services.CategoryService;
import br.com.fiap.netgifx.services.GifService;
import br.com.fiap.netgifx.utils.GifToPngConverter;
import br.com.fiap.netgifx.utils.InputStreamToBytesConverter;

@RequestScoped
@ManagedBean
public class GifController implements Serializable {
	private static final long serialVersionUID = 8740152239472998952L;

	private Gif gif;
	private String name;
	private List<Gif> gifList;
	private CategoryEntity categoryEntity;
	private List<CategoryEntity> categoriesEntity;
	private Genre genre;
	private Language language;
	private Rating rating;
	private UploadedFile uploadedFile;
	private byte[] snap = null;
	private byte[] image = null;

	@ManagedProperty("#{categoryService}")
	private CategoryService categoryService;

	@ManagedProperty("#{gifService}")
	private GifService gifService;

	@PostConstruct
	public void init() {
		this.categoriesEntity = this.categoryService.getCategories();
		clear();
		this.findAll();
	}

	private void clear() {
		this.gifList = new ArrayList<>();
		this.genre = null;
		this.language = null;
		this.rating = null;
		this.uploadedFile = null;
	}

	private void findAll() {
		this.gifList = this.gifService.findAll();
	}

	public void upload() {
		try {
			InputStream input = uploadedFile.getInputstream();
			this.snap = new InputStreamToBytesConverter().readBytes(new GifToPngConverter().convert(input));
			this.image = new InputStreamToBytesConverter().readBytes(input);
		} catch (IOException e) {
			e.printStackTrace();
		}
		this.addGif();
		this.findAll();
	}

	public void addGif() {
		Gif gif = new Gif();
		gif.setName(this.name);
		gif.setImageSnapshot(this.snap);
		gif.setFilename(this.uploadedFile.getFileName());
		gif.setImage(this.image);
		gif.setCategory(this.categoryEntity.convert(true));
		gif.setGenre(this.genre);
		gif.setLanguage(this.language);
		gif.setRating(this.rating);
		this.gifService.save(gif);
		this.findAll();
		this.clear();
	}

	public Gif getGif() {
		return gif;
	}

	public void setGif(Gif gif) {
		this.gif = gif;
	}

	public void setCategoryService(CategoryService service) {
		this.categoryService = service;
	}

	public List<CategoryEntity> getCategoriesEntity() {
		return categoriesEntity;
	}

	public void setCategoriesEntity(List<CategoryEntity> categoriesEntity) {
		this.categoriesEntity = categoriesEntity;
	}

	public CategoryEntity getCategoryEntity() {
		return categoryEntity;
	}

	public void setCategoryEntity(CategoryEntity categoryEntity) {
		this.categoryEntity = categoryEntity;
	}

	public void setGifService(GifService gifService) {
		this.gifService = gifService;
	}

	public List<Gif> getGifList() {
		return gifList;
	}

	public UploadedFile getUploadedFile() {
		return uploadedFile;
	}

	public void setUploadedFile(UploadedFile uploadedFile) {
		this.uploadedFile = uploadedFile;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Genre[] getGenres() {
		return Genre.values();
	}

	public Genre getGenre() {
		return genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	public Language getLanguage() {
		return language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Language[] getLanguages() {
		return Language.values();
	}

	public Rating getRating() {
		return rating;
	}

	public void setRating(Rating rating) {
		this.rating = rating;
	}

	public Rating[] getRatings() {
		return Rating.values();
	}

	public byte[] getSnap() {
		return snap;
	}

	public void setSnap(byte[] snap) {
		this.snap = snap;
	}

	public byte[] getImage() {
		return image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public CategoryService getCategoryService() {
		return categoryService;
	}

	public GifService getGifService() {
		return gifService;
	}

	public void setGifList(List<Gif> gifList) {
		this.gifList = gifList;
	}
	
}

Netgifx/WebContent/gif/create-gif.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/template.xhtml">
	<ui:define name="header" />
	<ui:define name="footer" />

	<ui:define name="content">
		<h:form id="Form" enctype="multipart/form-data">
		   <p:panel header="Criar Gif" style="margin-bottom:20px">
		        <h:panelGrid columns="2" cellpadding="5">
		            <h:outputLabel for="name" value="Nome:* " style="font-weight:bold"/>
		            <p:inputText id="name" value="#{gifController.name}" required="true" label="Nome"/>
		            
					<p:outputLabel value="Gênero:* " style="font-weight:bold"/>
					<p:selectOneMenu id="genre" value="#{gifController.genre}" required="true" >
						<f:selectItem itemValue="#{null}" itemLabel="Selecione..." noSelectionOption="true" />
						<f:selectItems value="#{gifController.genres}" var="var" itemLabel="#{var.text}" itemValue="#{var}" />
					</p:selectOneMenu>
		            
					<p:outputLabel value="Classificação:* " style="font-weight:bold"/>
					<p:selectOneMenu id="rating" value="#{gifController.rating}" required="true" >
						<f:selectItem itemValue="#{null}" itemLabel="Selecione..." noSelectionOption="true" />
						<f:selectItems value="#{gifController.ratings}" var="var" itemLabel="#{var}" itemValue="#{var}" />
					</p:selectOneMenu>
		            
					<p:outputLabel value="Categoria:* " style="font-weight:bold"/>
					<p:selectOneMenu id="category" value="#{gifController.categoryEntity}" converter="categoryConverter">
						<f:selectItem itemValue="#{null}" itemLabel="Selecione..." noSelectionOption="true" />
						<f:selectItems value="#{gifController.categoriesEntity}" var="cat" itemLabel="#{cat.name}" itemValue="#{cat}" />
					</p:selectOneMenu>
		            
					<p:outputLabel value="Idioma:* " style="font-weight:bold"/>
					<p:selectOneMenu id="language" value="#{gifController.language}">
						<f:selectItem itemValue="#{null}" itemLabel="Selecione..." noSelectionOption="true" />
						<f:selectItems value="#{gifController.languages}" var="var" itemLabel="#{var.text}" itemValue="#{var}" />
					</p:selectOneMenu>
	
					<p:outputLabel value="Arquivo:* " style="font-weight:bold"/>
					<p:fileUpload mode="simple" value="#{gifController.uploadedFile}" />

		            <p:commandButton id="btn_reset" value="Limpar" type="reset"/>
		            <p:commandButton id="btn_add" value="Salvar" update="gifs @parent" action="#{gifController.upload}" ajax="false" >
		                <p:collector value="#{gifController.gif}" addTo="#{gifController.gifList}" unique="true"/>
		            </p:commandButton>
		        </h:panelGrid>
		        
		    </p:panel>
		
		    <p:outputPanel id="gifs">
		        <p:dataTable value="#{gifController.gifList}" var="data" id="gifTable">
			
					<p:column>
						<f:facet name="header">
							<h:outputText value="Imagem" />
						</f:facet>
						<p:graphicImage width="100" value="#{gifStream.snapshot}">
							<f:param name="gifId" value="#{data.id}" />
						</p:graphicImage>
					</p:column>
		 
		            <p:column headerText="Código">
		                <h:outputText value="#{data.id}" />
		            </p:column>
		 
		            <p:column headerText="Nome">
		                <h:outputText value="#{data.name}" />
		            </p:column>
			
					<p:column>
						<f:facet name="header">
							<h:outputText value="Categoria" />
						</f:facet>
						<h:outputText value="#{data.category.name}" />
					</p:column>
		            
		            <p:column headerText="Gênero">
						<h:outputText value="#{data.genre.text}" />
					</p:column>
			
		            <p:column headerText="Idioma">
						<h:outputText value="#{data.language.text}" />
					</p:column>
			
		            <p:column headerText="Classificação">
						<h:outputText value="#{data.rating}" />
					</p:column>
					
		        </p:dataTable>
		    </p:outputPanel>
		</h:form>
	</ui:define>

</ui:composition>